version: 0.2


env:
  variables:
    S3_BUCKET: "forms-clone-frontend"
    CLOUDFRONT_DISTRIBUTION_ID: "E3UCQIYCSVV4R7"

cache:
  paths:
    - 'node_modules/**/*'

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing Node.js version $(node --version)
      - npm ci

  pre_build:
    commands:
      - echo Installing dependencies...

  build:
    commands:
      - echo Build started on `date`
      - npm run build

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Running tests...
      - echo "Syncing build output to S3..."
      - aws s3 sync build/ s3://$S3_BUCKET/ --delete
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: 'build'
  discard-paths: no


